<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>AgencyPortal_SmokeTest_WC</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>ssomasundaram@hastingsmutual.com;</mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>10b1b991-6aab-4e80-bd77-e01166f4d6b5</testSuiteGuid>
   <testCaseLink>
      <guid>a8b47efe-30e1-49f4-8cf0-76df29f78250</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Portal_WorkersCompensation/WC_SmokeTest_AllState/Portal_SmokeTest_MIState</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b392ec36-54f1-4dca-b119-f1fc981c2434</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6478a7f0-e5c4-44c7-9067-7d39eaa02d72</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b10f470-896c-4d21-9fac-e45e8ede3af6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d441d37b-170b-422b-bd76-338fda8836bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>685ae36e-66dd-43b4-b362-6f46def7b1c9</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
