<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_Contacts_Button_AddRole</name>
   <tag></tag>
   <elementGuidId>4e20886b-a4ec-4ac0-91f0-d4e60f6d003f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.gw-action--inner.gw-focus > div.gw-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='EditAccountContactPopup-ContactDetailScreen-AccountContactCV-ContactRolesDV-ContactRolesLV_tb-AddRoleButton']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1f182203-6f1c-4047-b479-50c47af4d473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-label</value>
      <webElementGuid>dbad0434-6969-41e0-9e76-0aa7d9d80d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Role</value>
      <webElementGuid>bd5a30ca-ba2e-4193-b16d-18b6c69a5310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EditAccountContactPopup-ContactDetailScreen-AccountContactCV-ContactRolesDV-ContactRolesLV_tb-AddRoleButton&quot;)/div[@class=&quot;gw-action--inner gw-focus&quot;]/div[@class=&quot;gw-label&quot;]</value>
      <webElementGuid>550f43bc-8782-4d17-bd57-c0217b792e56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EditAccountContactPopup-ContactDetailScreen-AccountContactCV-ContactRolesDV-ContactRolesLV_tb-AddRoleButton']/div/div[2]</value>
      <webElementGuid>31519d1d-dbe5-47ae-9428-d4dd1858e153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AR'])[1]/following::div[1]</value>
      <webElementGuid>aea05dcb-0b26-43ec-ae11-34a9b8c79fa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Addresses'])[1]/following::div[18]</value>
      <webElementGuid>bdf29684-debd-40ec-aaaf-494e2a93fbd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AC'])[1]/preceding::div[3]</value>
      <webElementGuid>b416d858-62c9-4aba-a9e3-931a4c9ca74d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accounting Contact'])[1]/preceding::div[5]</value>
      <webElementGuid>72cafa2b-8438-4b4c-9b7e-e1fdaed163f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Role']/parent::*</value>
      <webElementGuid>764f9773-cabd-41e2-b2bc-6b3a8c1feeb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div[2]/div/div/div[2]</value>
      <webElementGuid>ce8f9f1b-9e43-4a83-afae-8543d6b7f743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Add Role' or . = 'Add Role')]</value>
      <webElementGuid>fb5cb123-bc14-47fa-8504-49bb42071df5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
