<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Portal_LineCov_ConclusionExclusion_ 000305 - JointVenture</name>
   <tag></tag>
   <elementGuidId>2c12b91e-1aa7-4445-bb0c-8f79a297b926</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-20-option-2']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-20-option-2 > div.jut__LookupField__item > div.jut__LookupField__title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5953bc23-a31e-4451-9ec2-8a12f786a274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__LookupField__title</value>
      <webElementGuid>2a4ee8e4-7ad6-4f62-8249-379b4043d8e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WC 00 03 05 - Joint Venture As Insured Endorsement</value>
      <webElementGuid>f7f66cc7-d618-44b7-9d80-ceeabf0cffc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-20-option-2&quot;)/div[@class=&quot;jut__LookupField__item&quot;]/div[@class=&quot;jut__LookupField__title&quot;]</value>
      <webElementGuid>3a534d9a-9bfe-461f-9f5e-332700ef5fa0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-20-option-2']/div/div</value>
      <webElementGuid>4660079b-f35a-4fef-8abf-2d05f96ede08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unknown'])[2]/following::div[3]</value>
      <webElementGuid>5a154177-ae97-4de0-94fa-e459953697b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WC 00 03 04 - Insurance Company as Named Insured Endorsement'])[1]/following::div[4]</value>
      <webElementGuid>7dda095d-18d3-4599-a45c-d8fedf78e6ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unknown'])[3]/preceding::div[1]</value>
      <webElementGuid>c920df05-5660-4652-9a23-5ca025500397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WC 00 03 11 A - Voluntary Compensation And Employers Liability Coverage Endorsement'])[1]/preceding::div[2]</value>
      <webElementGuid>53aed702-683e-4f30-aa8d-3de40ff343a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='WC 00 03 05 - Joint Venture As Insured Endorsement']/parent::*</value>
      <webElementGuid>e5f41c74-0e7c-48b0-89b6-ee560860b911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[3]/div/div</value>
      <webElementGuid>5e9d3d52-d28b-4af5-991e-095e8c330668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'WC 00 03 05 - Joint Venture As Insured Endorsement' or . = 'WC 00 03 05 - Joint Venture As Insured Endorsement')]</value>
      <webElementGuid>452c0c75-d500-46b9-9cce-bc3d640d9ce9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
