<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CancelAdd Account</name>
   <tag></tag>
   <elementGuidId>0774cb4a-e14b-4d33-a997-7b4ac8084fc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.CreateUpdateView_buttonContainer__-bhDd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a969973c-62ef-420c-b9bc-fad0005fdf5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CreateUpdateView_buttonContainer__-bhDd</value>
      <webElementGuid>d6a3eba8-b355-4eee-891c-cf85e5f965ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CancelAdd Account</value>
      <webElementGuid>d5109b02-3900-474a-b272-a8acb94a9bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;PageContainer_standard__3bPCs&quot;]/div[@class=&quot;QuoteWizard_container__3EESf&quot;]/div[1]/div[@class=&quot;Wizard_bottomContainer__3lWO5&quot;]/div[2]/div[1]/div[@class=&quot;WizardPanel_body__21TLo&quot;]/div[1]/div[1]/div[@class=&quot;CreateUpdateView_formContainer__XCC_-&quot;]/div[@class=&quot;CreateUpdateView_buttonContainer__-bhDd&quot;]</value>
      <webElementGuid>61b67596-06ba-42b0-987e-7e82ff25a527</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div/div[4]</value>
      <webElementGuid>7002bbec-8f8b-4d82-8017-f5f6f4294754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select'])[1]/following::div[3]</value>
      <webElementGuid>f06a30ef-7808-4518-bd88-2cbf7d354757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Producer Code'])[1]/following::div[9]</value>
      <webElementGuid>1420fcae-41ad-49e3-9189-d32591aa6e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div[4]</value>
      <webElementGuid>8db7fea2-4f1c-4456-abd1-5751789a30fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'CancelAdd Account' or . = 'CancelAdd Account')]</value>
      <webElementGuid>ce53b35b-40f0-4be6-a9cf-f9c656ba37df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
