<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_0001-BrBlair 019550001BradfordBlair</name>
   <tag></tag>
   <elementGuidId>b0d733fa-4d97-4971-b264-dea61dc7b28b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-8-option-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-8-option-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>753eec9e-6f48-48ff-8a3d-4575038030e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicGenericSelectControl__option jut__GenericSelectControl__option jut__GenericSelectControl__optionFocused css-1n7v3ny-option</value>
      <webElementGuid>0539b94a-64b7-4ada-816b-1a53881afbe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-8-option-3</value>
      <webElementGuid>473c06bf-f383-46ae-b2a1-128d884a5a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>318be311-ff21-46f5-b264-00d9563132e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0001-BrBlair 019550001BradfordBlair</value>
      <webElementGuid>8aebe90a-bbc9-4e42-a9df-147c1dae939a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-8-option-3&quot;)</value>
      <webElementGuid>373d2f4d-cc66-40b2-92c2-b51134c5db92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-8-option-3']</value>
      <webElementGuid>904ac3f2-52f3-422e-8ed9-e48418e83d04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select'])[2]/following::div[3]</value>
      <webElementGuid>8a810c31-848f-4cbe-ae83-d5750534bc29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'react-select-8-option-3', '&quot;', ')')])[1]/following::div[7]</value>
      <webElementGuid>cb49942c-9111-4a70-acf0-3f9f4dd8d6af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0001-BrBlair 019550001BradfordBlair']/parent::*</value>
      <webElementGuid>9a9d2a21-cde9-4793-bcbb-6391e19fc267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[4]</value>
      <webElementGuid>596e4610-7d22-42b4-927d-0e3835350edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-8-option-3' and (text() = '0001-BrBlair 019550001BradfordBlair' or . = '0001-BrBlair 019550001BradfordBlair')]</value>
      <webElementGuid>978c4bc4-75a4-450d-ba63-8ce32f9738c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
