<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip Code_zipCode</name>
   <tag></tag>
   <elementGuidId>8903e5ea-0525-40c7-98b1-ad42bdc3f4b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#zipCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='zipCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>502990a9-5486-41f1-908a-0416aa79ac2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zipCode</value>
      <webElementGuid>f9d19ae2-0db5-4d40-9672-118ea5b7fc66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fc12b6ce-eaa3-45af-8115-4341dec118ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>edd11c6f-d614-4632-b92b-b6d695a01231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>a2634aa5-0aa8-4d6a-a6b6-0394d0ddb7ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f1bb111a-72eb-4329-aed0-fc0d6d5d1f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>zipCode_1440013438</value>
      <webElementGuid>105f5a53-9f5e-4842-a04c-7b9d533b40a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>ZIP</value>
      <webElementGuid>634b79d0-1b33-4050-8e57-6e86f7678740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ZIP</value>
      <webElementGuid>16234a1f-921b-4620-8748-f76c9c9d6b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zipCode&quot;)</value>
      <webElementGuid>f3012b48-a796-497f-b6d7-70cc55bef294</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='zipCode']</value>
      <webElementGuid>d6ed9b3c-ce89-48e0-87f5-43df3a59b366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div/div/div/div[2]/div[2]/div/div[3]/div[2]/input</value>
      <webElementGuid>24a79f38-487a-485f-8447-fcbacfcb6977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>de7e3e1f-911f-47ba-9227-1cbbd1708158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'zipCode' and @type = 'text' and @placeholder = 'ZIP']</value>
      <webElementGuid>8e82cbfc-eab9-4d88-8f4f-d0dbcb9148ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
